SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS coupon_issue;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS product_line;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS points;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;
